// <auto-generated />
using System;
using BDWalks.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BDWalks.API.Migrations
{
    [DbContext(typeof(BDWalksDbContext))]
    [Migration("20260401091833_Image domain Modified")]
    partial class ImagedomainModified
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BDWalks.API.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0776eec-aca2-46b0-8f62-646af060854f"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("1d9b6815-e737-4140-af40-e89139e8c7d0"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("54981894-cf6c-4851-9ecb-4a6437eb643b"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("BDWalks.API.Models.Domain.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("BDWalks.API.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("42bb729a-81f6-4b0a-b7bf-ff99f5d86024"),
                            Code = "DHK",
                            Name = "Dhaka"
                        },
                        new
                        {
                            Id = new Guid("e3e9e8da-c649-47c9-9273-e0addeff942b"),
                            Code = "CTG",
                            Name = "Chattogram"
                        },
                        new
                        {
                            Id = new Guid("952175e9-f4ee-45b7-a551-ce1a88aaa66b"),
                            Code = "BSL",
                            Name = "Barishal"
                        },
                        new
                        {
                            Id = new Guid("ca440154-92dd-45bb-8ccb-b44ac96718dd"),
                            Code = "KLN",
                            Name = "Khulna"
                        },
                        new
                        {
                            Id = new Guid("15d083e1-d140-4401-8227-1c73084fc2bc"),
                            Code = "MNS",
                            Name = "Mymensingh"
                        },
                        new
                        {
                            Id = new Guid("4b4f56b0-e6ca-4201-bd4f-8d380e95c7a7"),
                            Code = "RJH",
                            Name = "Rajshahi"
                        },
                        new
                        {
                            Id = new Guid("1a087eb9-a88e-40f5-b524-a9a933b2d281"),
                            Code = "RNP",
                            Name = "Rangpur"
                        },
                        new
                        {
                            Id = new Guid("7724d32a-8cae-4fa8-b2f7-ae9255e3c12d"),
                            Code = "SLT",
                            Name = "Sylhet"
                        });
                });

            modelBuilder.Entity("BDWalks.API.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("BDWalks.API.Models.Domain.Walk", b =>
                {
                    b.HasOne("BDWalks.API.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BDWalks.API.Models.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
